create table if not exists kul (
  id INT(11) NOT NULL auto_increment,
  tc varchar(11) NOT NULL,
  ad varchar(32),
  soyad varchar(32),
  kizliksoyad varchar(32),
  babaad varchar(32),
  anaad varchar(32),
  dogumgun varchar(2),
  dogumay varchar(2),
  dogumyil varchar(4),
  dogumil varchar(32),
  dogumilce varchar(32),
  ceptel varchar(10),
  evtel varchar(10),
  email varchar(100),
  evadres varchar(100),
  il varchar(32),
  ilce varchar(32),
  uni varchar(100),
  yokul varchar(100),
  calismakurum varchar(100),
  calismabirim varchar(100),
  isadres varchar(100),
  isil varchar(32),
  isilce varchar(32),
  onkayit varchar(1),
  tarih DATE,
  saat TIME,
  dogumulke varchar(64),
  PRIMARY KEY(id)
);
